### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###


###
GET http://127.0.0.1:8080/login

Content-Type: application/json

{
  "username": "Henk",
  "password": "Henk is ok!"
}

> {%
    client.global.set("userToken", response.body.token);
%}

### get me
GET http://127.0.0.1:8080/meAsUser
Authorization: Bearer {{userToken}}

